apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-aks-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-aks-app
  template:
    metadata:
      labels:
        app: java-aks-app
    spec:
      containers:
        - name: java-aks-app
          image: ram1993/java-aks-app:latest
          ports:
            - containerPort: 8080

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 5

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 5